version: "3.8"
services:
     db:
          image: mysql:8.0.36-debian
          command: --default-authentication-plugin=mysql_native_password
          environment:
               MYSQL_ROOT_PASSWORD: rootpassword
               MYSQL_DATABASE: e-commerces
               MYSQL_USER: mysql
               MYSQL_PASSWORD: 123456
          volumes:
               - db_data:/var/lib/mysql
          expose:
               - 3307
          ports:
               - 3307:3307
     backend:
          build:
               context: .
               target: dev
          env_file:
               - .env
          command: npm start
          ports:
               - "7070:7070"
          depends_on:
               - db
          # volumes:
          #      - ./:/app
          #      - /app/node_modules/
          volumes:
               - ./src:/usr/src/app/src
volumes:
     db_data:
